services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - devcodingnetwork
    ports:
      - 6379:6379

  app:
    build: .
    depends_on:
      - db
    networks:
      - devcodingnetwork
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app

networks:
  devcodingnetwork:
    driver: bridge

volumes:
  mysql:
